Repository Requisitos-de-Software/2023.1-Caesb, pull requests merged in 2023-04, with the labels that each got.

#19 Corrigindo heatmap
  docs/Planejamento/heatmap.md
  site/Planejamento/heatmap/index.html
  site/search/search_index.json
  site/sitemap.xml.gz
Labels: bug, documentation

#35 Correcão da aba de Guias
  docs/Guia/AdicionandoIcones.md
  docs/index.md
Labels: documentation, revisão

#38 correcao de link
  docs/Planejamento/ferramentas.md
Labels: fixing
